// code for number guessing game

#include <iostream>
#include <ctime>
using namespace std;

int main(){
    int number;
    int guess;
    int attempts=0;
    srand(time(NULL));                 // initialised the random number generator
    number = rand() % 101;            // generates a random number between 1 to 100
    cout<<"**********welcome**********\n";
    cout<<"**Number Guessing Game**\n";
    while(true){

        cout<<"\nenter a guess between 0-100 : ";
        cin>>guess;
       
        
        
        if(guess>100 || guess<0){

            cout<<"invalid range of input";
            continue;
    }

    
        
        if(guess==number){

            cout<<"yayyy!! you won the game.\nThe number you guessed is same as the nummber generated by machine.\n";
            attempts++;

            cout<<"total number of attempts you took was "<<attempts;
            
        }
        else if(guess>number){


            cout<<"your guess is higher than the number generated\n";
            
            attempts++;
            cout<<"number of attempts till now "<<attempts;
        }
        else if(guess<number){


            cout<<"your guess is lower than the number generated\n";
            attempts++;
            cout<<"number of attempts till now "<<attempts;
        }
        else{

            cout<<"please enter numerical input!!!"
        }
        



    }

    return 0;
}


